describe("Navigation Bar Test",()=>{
    it("navigate and popup check",()=>{
        cy.visit("/login")
        .get("input[placeholder='Email']").type("dharshanramk@gmail.com")
        .get("input[placeholder='Password']").type("Admin@123")
        .get("button").contains("Sign in").click()
        .get("nav").get("img[alt='Logo']")
        .get(".nav-link-with-margin.nav-link[href='/dashboard']").contains("HOME").click()
        .get(".nav-link-with-margin.nav-link[href='/booking']").contains("BOOKING").click()
        .get(".nav-link-with-margin.nav-link[href='/peak-season']").contains("PEAK SEASON").click()
        // .get(".nav-link-with-margin.nav-link[href='/payments']").contains("PAYMENTS").click()
        .get(".nav-link-with-margin.nav-link[href='/faq']").contains("FAQ").click()
        .get(".MuiBox-root.css-1hg4z9e").click()
        .get("div[id='account-menu'] li:nth-child(1)").contains("Profile")
        .get("div[id='account-menu'] li:nth-child(2)").contains("Reset")
        .get(".css-kk1bwy-MuiButtonBase-root-MuiMenuItem-root").contains("Add another account")
        .get(".css-kk1bwy-MuiButtonBase-root-MuiMenuItem-root").contains("Logout")
    })
})