describe("Dashboard and Navigation check", () => {
    it("Navigate to all properties from dashboard", () => {
        cy.visit("/login")
            .get("input[placeholder='Email']").type("owner@fraxioned.com")
            .get("input[placeholder='Password']").type("Owner@123")
            .get("button").contains("Sign in").click()
            .get("body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(6) > div:nth-child(1)")
            .click().wait(1500)
            .url().should('include','/booking').go(-1)
            .get("body > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div:nth-child(6) > div:nth-child(2)")
            .click().wait(1500)
            .url().should('include','/booking').go(-1)
            .get(".card3.static-card").click().wait(1500)
            .url().should('include','/booking').go(-1)
            .get(".plus-icon").click()
    })      
})