describe("Check Booking Functionalities", () => {
    it("Sidebar toggle check", () => {
        cy.visit("/login")
            .get("input[placeholder='Email']").type("fraxionedownersportal@gmail.com")
            .get("input[placeholder='Password']").type("Admin@123")
            .get("button").contains("Sign in").click()
            .get(".sidepanel-module__toggleButton___YfTUu").click().wait(2000)
            .get(".sidepanel-module__logoContainer___XyiIp").click().wait(2000);
    })
    it("Should have month,week and holiday buttons", () => {
        cy.visit("/login")
            .get("input[placeholder='Email']").type("fraxionedownersportal@gmail.com")
            .get("input[placeholder='Password']").type("Admin@123")
            .get("button").contains("Sign in").click()
            .get("button").contains("Week").click().wait(1000)
            .get("button").contains("Day").click().wait(1000)
            .get("button").contains("Month").click().wait(1000)
    })
    it("Should route previous month and next month", () => {
        cy.visit("/login")
            .get("input[placeholder='Email']").type("fraxionedownersportal@gmail.com")
            .get("input[placeholder='Password']").type("Admin@123")
            .get("button").contains("Sign in").click()
            .get("button").contains("Back").click().wait(1000)
            .get("button").contains("Next").click().wait(1000)
            .get("button").contains("Today").click().wait(1000)
            cy.get("nav")
            .get("img[alt='User']").click()
            .get('li').contains("Logout").click().wait(2000)
            .get(".btn-confirm").contains("Logout").click()
    })
})